/*
CREATE DATABASE SmartBook;
USE SmartBook;
*/

INSERT INTO Users (Username, Email, Password)
VALUES (N'aliceReader', N'alice@example.com', N'$2a$10$alicehash1'),
       (N'bobWriter', N'bob@example.com', N'$2a$10$bobhash1'),
       (N'carolUser', N'carol@example.com', N'$2a$10$carolhash1'),
       (N'davidDev', N'david@example.com', N'$2a$10$davidhash1'),
       (N'eveResearch', N'eve@example.com', N'$2a$10$evehash1'),
       (N'frankTest', N'frank@example.com', N'$2a$10$frankhash1'),
       (N'graceQA', N'grace@example.com', N'$2a$10$gracehash1'),
       (N'henryAdmin', N'henry@example.com', N'$2a$10$henryhash1'),
       (N'ivyAuthor', N'ivy@example.com', N'$2a$10$ivyhash1'),
       (N'jackScholar', N'jack@example.com', N'$2a$10$jackhash1'),
       (N'karenReader', N'karen@example.com', N'$2a$10$karenhash1');

INSERT INTO Authors (Name, Bio)
VALUES (N'George Orwell', N'Dystopian novelist and essayist.'),
       (N'J.K. Rowling', N'Author of the Harry Potter series.'),
       (N'Haruki Murakami', N'Blends realism with surreal elements.'),
       (N'Margaret Atwood', N'Canadian novelist, feminist themes.'),
       (N'Chinua Achebe', N'Nigerian author of African classics.'),
       (N'Isaac Asimov', N'Science fiction visionary.'),
       (N'Jane Austen', N'English novelist of romantic fiction.'),
       (N'Ernest Hemingway', N'Master of concise prose.'),
       (N'Leo Tolstoy', N'Russian realist author.'),
       (N'Fyodor Dostoevsky', N'Philosophical and psychological novels.'),
       (N'Agatha Christie', N'Mystery and detective fiction.'),
       (N'Stephen King', N'Horror and supernatural tales.'),
       (N'Neil Gaiman', N'Fantasy and mythological fiction.'),
       (N'J.R.R. Tolkien', N'High fantasy author.'),
       (N'Brandon Sanderson', N'Modern fantasy epic writer.'),
       (N'Arthur C. Clarke', N'Science and speculative fiction.'),
       (N'Maya Angelou', N'Poet and memoirist.'),
       (N'Gabriel García Márquez', N'Magical realism.'),
       (N'Dan Brown', N'Thrillers involving history and religion.'),
       (N'Yuval Noah Harari', N'Historian and futurist writer.');

INSERT INTO Categories (Name)
VALUES (N'Fiction'),
       (N'Science Fiction'),
       (N'Mystery'),
       (N'Biography'),
       (N'Fantasy'),
       (N'Historical'),
       (N'Philosophy'),
       (N'Romance'),
       (N'Thriller'),
       (N'Non-fiction');

INSERT INTO Books (Title, AuthorId, CategoryId)
VALUES (N'1984', 1, 2),
       (N'Animal Farm', 1, 2),
       (N'Harry Potter and the Sorcerer''s Stone', 2, 5),
       (N'Kafka on the Shore', 3, 1),
       (N'The Handmaid''s Tale', 4, 2),
       (N'Things Fall Apart', 5, 1),
       (N'I, Robot', 6, 2),
       (N'Pride and Prejudice', 7, 8),
       (N'The Old Man and the Sea', 8, 1),
       (N'War and Peace', 9, 6),
       (N'Crime and Punishment', 10, 7),
       (N'Murder on the Orient Express', 11, 3),
       (N'The Shining', 12, 3),
       (N'American Gods', 13, 5),
       (N'The Hobbit', 14, 5),
       (N'Mistborn', 15, 5),
       (N'Rendezvous with Rama', 16, 2),
       (N'I Know Why the Caged Bird Sings', 17, 4),
       (N'One Hundred Years of Solitude', 18, 1),
       (N'The Da Vinci Code', 19, 9),
       (N'Sapiens', 20, 10),
       (N'Inferno', 19, 9),
       (N'Homo Deus', 20, 10),
       (N'And Then There Were None', 11, 3),
       (N'Elantris', 15, 5),
       (N'Love in the Time of Cholera', 18, 1),
       (N'Emma', 7, 8),
       (N'To the Lighthouse', 7, 1),
       (N'Dune', 6, 2),
       (N'The Silmarillion', 14, 5),
       (N'A Farewell to Arms', 8, 6),
       (N'Anna Karenina', 9, 6),
       (N'The Idiot', 10, 7),
       (N'Coraline', 13, 5),
       (N'The Road', 6, 2),
       (N'The Name of the Wind', 15, 5),
       (N'The Alchemist', 18, 1),
       (N'Becoming', 17, 4),
       (N'Angels and Demons', 19, 9),
       (N'The Testaments', 4, 2),
       (N'The Casual Vacancy', 2, 1),
       (N'Norwegian Wood', 3, 1),
       (N'Salem''s Lot', 12, 3),
       (N'Foundation', 6, 2),
       (N'The Power', 4, 2),
       (N'Persuasion', 7, 8),
       (N'The Sun Also Rises', 8, 6),
       (N'A Study in Scarlet', 11, 3),
       (N'Down and Out in Paris and London', 1, 4),
       (N'The Ocean at the End of the Lane', 13, 5);

INSERT INTO UserBooks (UserId, BookId, IsRead, Rating)
VALUES (1, 1, 1, 5),
       (1, 2, 1, 5),
       (1, 3, 0, NULL),
       (1, 4, 1, 4),
       (1, 5, 1, 3),
       (2, 6, 1, 5),
       (2, 7, 0, NULL),
       (2, 8, 1, 5),
       (2, 9, 0, NULL),
       (2, 10, 1, 4),
       (3, 11, 1, 4),
       (3, 12, 1, 4),
       (3, 13, 0, NULL),
       (3, 14, 1, 5),
       (3, 15, 0, NULL),
       (4, 16, 0, NULL),
       (4, 17, 1, 4),
       (4, 18, 1, 4),
       (4, 19, 1, 5),
       (4, 20, 1, 5),
       (5, 21, 1, 3),
       (5, 22, 1, 4),
       (5, 23, 1, 4),
       (5, 24, 0, NULL),
       (5, 25, 1, 5),
       (6, 26, 0, NULL),
       (6, 27, 0, NULL),
       (6, 28, 1, 5),
       (6, 29, 1, 4),
       (6, 30, 0, NULL),
       (7, 31, 1, 3),
       (7, 32, 1, 4),
       (7, 33, 0, NULL),
       (7, 34, 1, 5),
       (7, 35, 1, 4),
       (8, 36, 0, NULL),
       (8, 37, 1, 5),
       (8, 38, 1, 5),
       (8, 39, 0, NULL),
       (8, 40, 1, 4),
       (9, 41, 1, 5),
       (9, 42, 1, 3),
       (9, 43, 0, NULL),
       (9, 44, 0, NULL),
       (9, 45, 1, 4),
       (10, 46, 1, 5),
       (10, 47, 0, NULL),
       (10, 48, 1, 4),
       (10, 49, 1, 4),
       (10, 50, 1, 5),
-- Duplicates across users
       (2, 1, 1, 5),
       (3, 1, 1, 5),
       (4, 1, 1, 4),
       (5, 1, 0, NULL),
       (6, 1, 1, 3),
       (7, 2, 0, NULL),
       (8, 2, 1, 4),
       (9, 2, 1, 5),
       (10, 2, 1, 3),
       (1, 6, 1, 5),
       (3, 10, 1, 4),
       (6, 11, 1, 5),
       (7, 15, 1, 5),
       (8, 16, 1, 4),
       (9, 17, 0, NULL);
