/*
CREATE DATABASE SmartBook;
USE SmartBook;
*/

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL
);

CREATE TABLE Authors (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Bio NVARCHAR(MAX) NULL
);

CREATE TABLE Categories (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Books (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(255) NOT NULL,
    AuthorID INT NOT NULL,
    CategoryID INT NOT NULL,
    UserID INT NOT NULL,
    IsRead BIT NOT NULL DEFAULT 0,
    Rating INT CHECK (Rating BETWEEN 0 AND 5),

    CONSTRAINT FK_Books_Authors FOREIGN KEY (AuthorID) REFERENCES Authors(Id),
    CONSTRAINT FK_Books_Categories FOREIGN KEY (CategoryID) REFERENCES Categories(Id),
    CONSTRAINT FK_Books_Users FOREIGN KEY (UserID) REFERENCES Users(Id)
);
