name: Build and Publish WPF .NET 8 App
permissions:
  contents: read
  actions: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Clean build outputs
        run: dotnet clean --configuration Release

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build SmartBook.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish
        run: dotnet publish SmartBook.csproj -c Release -r win-x64 --self-contained true --output ./publish

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartBook
          path: ./publish
